name: release
on:
  push:
    branches:
      - master
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'skip ci') == false || contains(github.actor, 'bot') == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci
      - name: Bundle
        run: npm run bundle
      - uses: ./
        if: contains(github.actor, 'bot') == false
        with:
          SERVICE_PREFIX: DEFAULT
        env:
          DEFAULT_TEST_KEY: TEST_SECRET
          AZURE_CLIENT_ID: 6b37a34b-4496-47e2-ab31-1bc31926e797
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: 5a7d1f14-292f-4043-a73a-d0339418a1e1
          AZURE_VAULT_URI: https://tvkv-dev-top-01.vault.azure.net/
      - name: check
        run: echo $DEFAULT_TEST_KEY
